### ISSUE TITLE
How to initialize client?

### ISSUE THREAD

**Issue by alexcurtin** [dasnixon/statuspageio#1]
Hi @dasnixon I was hoping you could help me figure out if I am creating the client correctly:

```
blah = Statuspageapi::new(:api_key => "redacted", :page_id => "redacted")
```

**Comment by thechrisnixon** [comment]
Is this in a ruby or rails app?

**Comment by alexcurtin** [comment]
I am just making a ruby app trying to get this gem in a working shape, made some minor adjustments and stuff but i'm not that great at ruby to be frank. I've got it working now with some minor changes, but can't get the request.rb to work properly. The get method is available but the headers aren't being passed in, requiring me to adjust my incidents.rb to:


```
require 'statuspageapi/request'
require "statuspageapi/client"
require "statuspageapi/configuration"

module Statuspageapi
    class Client
      module Incident
        def incidents(scope = :all)
          case scope
          when :all
            Request.get("/pages/#{self.page_id}/incidents", :headers => headers)
          when :unresolved
            Request.get("/pages/#{self.page_id}/incidents/unresolved")
          when :scheduled
            Request.get("/pages/#{self.page_id}/incidents/scheduled")
          else
            Request.get("/pages/#{self.page_id}/incidents")
          end
        end

        def headers
          { Authorization: "OAuth #{self.api_key}" }
        end
      end
    end
  end
```

which is working for now (just testing incident get method). I don't know why the request.rb `headers: headers` isn't working. Perhaps `#{self.api_key}` is not set/available in that module? 

@dasnixon

**Comment by thechrisnixon** [comment]
@alexcurtin I updated the gem to `0.1.2` and made some fixes.

You can do:

`client = Statuspageio::Client.new(api_key: '<api_key>', page_id: '<page_id>')`
`client.incidents(:all) #list of all incidents`

LMK what other endpoints you might want to use this for, I randomly made this gem on a whim but never moved forward with it. Now that someone found use for it I can build it out.

**Comment by alexcurtin** [comment]
@dasnixon thanks a ton! I am trying to use this + learn ruby, do you mind if I open some PR's to this gem in the near future for you to review/merge? The statuspage api docs are decent, but they don't link out to any standard language libraries (I found one for Golang and a different, 5 year old Ruby one).

**Comment by thechrisnixon** [comment]
Yea go for it 👍
